# Generated by Django 3.1.5 on 2021-01-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_address_admin_cart_cartitem_customer_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemimage',
            field=models.FileField(blank=True, default='tea.jpg', upload_to='media/'),
        ),
    ]
