# Generated by Django 3.1.5 on 2021-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_product_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='itemimage',
            field=models.FileField(blank=True, default='tea.jpg', upload_to='media/'),
        ),
    ]
