# Generated by Django 3.1.5 on 2021-01-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_cartitem_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='itemimage',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
