# Generated by Django 3.1.5 on 2021-01-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_auto_20210117_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemimage',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
