# Generated by Django 3.1.6 on 2021-02-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0010_address_admin_cart_cartitem_customer_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
